In [9]:
from fvector import vector_add,  vector_sum, scalar_multiply

In [10]:
vector_add([1,2,4],[0,2,3])

[1, 4, 7]

In [11]:
scalar_multiply(3,[1, 2])

[3, 6]

In [12]:
import math

In [13]:
math.sqrt(5)

2.23606797749979

In [32]:
import numpy as np
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,9]], dtype=np.float64)    # Create a rank 2 array
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,9]], dtype=np.float64)
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0]) 

(4, 3)
1.0 2.0 4.0


In [35]:
np.add(a,b)

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.],
       [20., 22., 18.]])

In [30]:
bool_idx = (b > 4)
b[bool_idx]

array([ 5,  6,  7,  8,  9, 10, 11,  9])

In [36]:
np.multiply(a, b)

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.],
       [ 49.,  64.,  81.],
       [100., 121.,  81.]])

In [37]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.        ]])

In [40]:
a.dot(b.transpose())

array([[ 14.,  32.,  50.,  59.],
       [ 32.,  77., 122., 149.],
       [ 50., 122., 194., 239.],
       [ 59., 149., 239., 302.]])

In [48]:
a

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11.,  9.]])

In [44]:
a[0].dot(b[0])

14.0

In [49]:
np.sum(a, axis=1)

array([ 6., 15., 24., 30.])

In [50]:
a.T

array([[ 1.,  4.,  7., 10.],
       [ 2.,  5.,  8., 11.],
       [ 3.,  6.,  9.,  9.]])

In [56]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, a.T.shape)

In [57]:
vv

array([[1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1],
       [1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1],
       [1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1]])

In [65]:
np.dot(x,vv)


array([[ 6,  0,  6,  6,  0,  6,  6,  0,  6,  6,  0,  6],
       [15,  0, 15, 15,  0, 15, 15,  0, 15, 15,  0, 15],
       [24,  0, 24, 24,  0, 24, 24,  0, 24, 24,  0, 24],
       [33,  0, 33, 33,  0, 33, 33,  0, 33, 33,  0, 33]])

In [66]:
v = np.array([1,2,3]) 
w = np.array([4,5]) 

In [69]:
w.shape


(2,)

In [74]:
np.reshape(v, (3, 1))

array([[1],
       [2],
       [3]])

In [76]:
w*np.reshape(v, (3, 1)) 

array([[ 4,  5],
       [ 8, 10],
       [12, 15]])

In [77]:
x = np.array([[1,2,3], [4,5,6]])

In [80]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
print(x + v)

[[2 4 6]
 [5 7 9]]


In [88]:
(x.T+w).T

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [86]:
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [92]:
from scipy.spatial.distance import pdist, squareform

x = np.array([[0, 1], [1, 0], [2, 0]])
print(x)

d = squareform(pdist(x, 'euclidean'))
print(d)

[[0 1]
 [1 0]
 [2 0]]
[[0.         1.41421356 2.23606798]
 [1.41421356 0.         1.        ]
 [2.23606798 1.         0.        ]]


In [101]:
x.shape

(3, 2)

In [97]:
3**(1/2)

1.7320508075688772

In [98]:
2.23606798**2

5.000000011181281